# Pipelines In sklearn

### Project Implementation without Pipeline

In [10]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [12]:
df = pd.read_csv("DATASET/titanic.csv")

In [13]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [14]:
# drop unnecessary column 
df.drop(columns=['PassengerId','Ticket','Name','Cabin'],inplace=True)

In [15]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C
2,1,3,female,26.0,0,0,7.9250,S
3,1,1,female,35.0,1,0,53.1000,S
4,0,3,male,35.0,0,0,8.0500,S


In [16]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                df['Survived'],test_size=0.2,random_state=42)

In [17]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [34]:
# apply simple Imputer on age column
si_age = SimpleImputer()
si_embarked =SimpleImputer(strategy='most_frequent')

X_train_age =si_age.fit_transform(X_train[['Age']])
X_train_embarked =si_embarked.fit_transform(X_train[['Embarked']])

X_test_age =si_age.transform(X_test[['Age']])
X_test_embarked =si_embarked.transform(X_test[['Embarked']])

In [35]:
# one hot encoding on Sex and embarked
one_S = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
one_E = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
X_train_S =one_S.fit_transform(X_train[['Sex']])
X_train_E =one_E.fit_transform(X_train[['Embarked']])

X_test_S =one_S.transform(X_test[['Sex']])
X_test_E =one_E.transform(X_test[['Embarked']])

In [36]:
X_train_remain = X_train.drop(columns=['Sex','Age','Embarked'])
X_test_remain =X_test.drop(columns=['Sex','Age','Embarked'])

In [37]:
# concatenate karo
X_train_transformed =np.concatenate((X_train_remain,X_train_age,X_train_E,X_train_S),axis=1)
X_test_transformed =np.concatenate((X_test_remain,X_test_age,X_test_E,X_test_S),axis=1)

In [39]:
X_train_transformed

array([[1., 0., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 2., 0., ..., 0., 0., 1.],
       [1., 1., 2., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 0., 1.]], shape=(712, 11))

In [40]:
model = DecisionTreeClassifier()
model.fit(X_train_transformed,y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [44]:
y_pred  = model.predict(X_test_transformed)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1])

In [42]:
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y_test,y_pred)


In [43]:
acc_score

0.7877094972067039

In [46]:
#  save the model 
import  pickle
pickle.dump(one_S,open('models/OHE_sex.pkl','wb'))
pickle.dump(one_E,open('models/OHE_embarked.pkl','wb'))
pickle.dump(model,open('models/model_clf.pkl','wb'))

In [138]:
# prediction without using pipeline
import pickle
import numpy as np

one_S = pickle.load(open('models/OHE_sex.pkl','rb'))
one_E = pickle.load(open('models/OHE_embarked.pkl','rb'))
model = pickle.load(open('models/model_clf.pkl','rb'))

# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

test_input_sex = one_S.transform(test_input[:,1].reshape(1,1))
test_input_embarked = one_E.transform(test_input[:,-1].reshape(1,1))
test_input_age = test_input[:,2].reshape(1,1)

test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

model.predict(test_input_transformed)

/home/tushar/Desktop/MLandDL/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/home/tushar/Desktop/MLandDL/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([1])

### Project Implementation using pipeline

In [70]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2


In [71]:
df = pd.read_csv("DATASET/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [72]:
df.drop(columns=['PassengerId','Ticket','Name','Cabin'],inplace=True)

In [73]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C
2,1,3,female,26.0,0,0,7.9250,S
3,1,1,female,35.0,1,0,53.1000,S
4,0,3,male,35.0,0,0,8.0500,S


In [87]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                df['Survived'],test_size=0.2,random_state=42)

In [89]:
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>


In [90]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S
...,...,...,...,...,...,...,...
106,3,female,21.0,0,0,7.6500,S
270,1,male,NaN,0,0,31.0000,S
860,3,male,41.0,2,0,14.1083,S
435,1,female,14.0,1,2,120.0000,S


In [91]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [103]:
# imputation transformer 
# yaha pe you can use column name but jab transformation hoga to np array banega na ki dataframe 
# code may break in pipeline so use index
t1 =ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])
],remainder='passthrough')

In [104]:
# encoding transformer 
t2 =ColumnTransformer([
    ('one_sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

In [94]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [95]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [105]:
# scaling transformer
# now apne pas 8 col hai after encoding sex ke 2 column banege and embarked ke 3
# to 8 maise 2 col gaye bache 6 and ye encoding ke bad ke 5 so 11 
t3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,11))
])

In [106]:
#feature selection
t4 =SelectKBest(score_func=chi2,k=5)

In [107]:
# train a model
t5 =DecisionTreeClassifier()

In [108]:
# create a pipeline
training_pipeline =Pipeline([
    ('t1',t1),
    ('t2',t2),
    ('t3',t3),
    ('t4',t4),
    ('t5',t5)
])

In [109]:
# using make_pipeline function
train_pipeline = make_pipeline(t1,t2,t3,t4,t5)

In [110]:
# display pipeline 
from sklearn import set_config
set_config(display='diagram')

In [112]:
# fit your pipeline
# isme agar model train nhi kar rhe to fit_transform use karo 

training_pipeline.fit(X_train,y_train)

,steps,"[('t1', ...), ('t2', ...), ...]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('impute_age', ...), ('impute_embarked', ...)]"
,remainder,'passthrough'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [115]:
training_pipeline.steps# this gives an array (named_steps give an dict)

[('t1',
  ColumnTransformer(remainder='passthrough',
                    transformers=[('impute_age', SimpleImputer(), [2]),
                                  ('impute_embarked',
                                   SimpleImputer(strategy='most_frequent'),
                                   [6])])),
 ('t2',
  ColumnTransformer(remainder='passthrough',
                    transformers=[('one_sex_embarked',
                                   OneHotEncoder(handle_unknown='ignore',
                                                 sparse_output=False),
                                   [1, 6])])),
 ('t3',
  ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 11, None))])),
 ('t4', SelectKBest(k=5, score_func=<function chi2 at 0x783d61545000>)),
 ('t5', DecisionTreeClassifier())]

In [118]:
# predict 
y_pred = training_pipeline.predict(X_test)

from sklearn.metrics import accuracy_score
acc_sc = accuracy_score(y_test,y_pred)
print(acc_sc)

0.6256983240223464


In [120]:
# cross validation using pipeline
from sklearn.model_selection import cross_val_score
cross_val_score(training_pipeline,X_train,y_train,scoring='accuracy').mean()

np.float64(0.6391214419383433)

In [129]:
# grid search using pipeline
params ={
    't5__max_depth':[1,2,3,4,5,None]
}

In [130]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(training_pipeline,params,cv=5,scoring='accuracy')
grid.fit(X_train,y_train)

,estimator,Pipeline(step...lassifier())])
,param_grid,"{'t5__max_depth': [1, 2, ...]}"
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,transformers,"[('impute_age', ...), ('impute_embarked', ...)]"


In [131]:
grid.best_score_

np.float64(0.6391214419383433)

In [132]:
grid.best_params_

{'t5__max_depth': 3}

In [133]:
# Exporting pipeline
import pickle
pickle.dump(training_pipeline,open('models/pipe.pkl','wb'))

In [135]:
# use  the exported pipeline/model 
import pickle
import numpy as np

# encode
training_pipeline=pickle.load(open('models/pipe.pkl','rb'))

# input
test_input =np.array([2	,'male',23.0,0,0,13.0000,'C'],dtype=object,).reshape(1,7)
training_pipeline.predict(test_input)

/home/tushar/Desktop/MLandDL/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
/home/tushar/Desktop/MLandDL/venv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([1])